<a href="https://colab.research.google.com/github/aayussraut/Exploring_NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x=np.array([[1,2,3],[4,5,6,6]])
print("x:\n{}".format(x))

x:
[list([1, 2, 3]) list([4, 5, 6, 6])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


## **NumPy**
- extension package to Python for multi-diensional arrays
- closer to hardware
- designed for scinetific computation
- aslo known as array oriented computing.


#### **array**
- is central data structure of the Numpy library.
- the elements in array are of same type

In [ ]:
import numpy as np

In [ ]:
#example
a=np.array([1,2,3,4,5])  # of int type
a=np.array([[1,2,3,4],[4,5,6,7]])  #list type

In [ ]:
#accessing elements

print(a[0])

[1 2 3 4]


##### Attributes of an array

- the no of dimensions and items in an array is defined by iys shape
- the shape of an array is a tuple of nonnegative intergers that specufy the sized of each dimension.

- suppose we have a 2D array that looks like:

[[0., 0., 0.],

 [1., 1., 1.]]

- It means our array has 2 axes. THe first axis has a length of 2 and second axis has a length of 3.



#### **Creating a Basic Array**

-np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [2]:
import numpy as np

In [ ]:
#np.array()
# To create a Numpy array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
#np.zeros()
# to create an array filled with 0's
np.zeros(2)

array([0., 0.])

In [ ]:
#np.ones()
# to cerate an array filled with 1's
np.ones(1)

array([1.])

In [ ]:
#np.zeros

# creates an array whose initial content is random and depends on the state of the memory
# the reasons ti use empty over zeros is speed

np.empty(2)

array([0., 0.])

In [ ]:
#np.arange()

# to create an array with a range of elements

np.arange(4)


array([0, 1, 2, 3])

In [ ]:
# to create an array that contains a range of evenly spaced intervals.

np.arange(2,9,2)


array([2, 4, 6, 8])

In [ ]:
#np.linspace()

# to create an array with values that are spaced linearly in specified interval

np.linspace(0,10,num=5)

# num= 5 means .. 5 no. between 0 and 10

In [ ]:
np.linspace(0,10,num=5 ,endpoint=False)
# returns 5 no between 0 and 10 where 10 is excluded.

array([0., 2., 4., 6., 8.])

In [ ]:
#dtype

#specifying data type

np.ones(2,dtype=np.int64)

array([1, 1])

#### Adding, removing and sorting elements

- np.sort(),np.concatenate()

In [3]:
#np.sort()

arr=np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
#np.partition 

# -rearranges the elements of kth position(i.e. 3 in example) such a way that All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. 
a=np.array([4,2,8,6,10])
np.partition(a,3)

array([ 6,  4,  2,  8, 10])

In [8]:
#np.concatenate()

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### **Shape and size of array**
- ndarray.ndim : tell us the number of axes,or dimensions, of the array

- ndarray.size : tell us the total number of elements of the array's shape

- ndarray.shape : will display a tuple of integers that indiacate the number of elements stored along each dimension of the array.

In [9]:
array_example =np.array([[[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]]])


In [10]:
array_example.ndim

3

In [11]:
array_example.size

24

In [12]:
array_example.shape

(3, 2, 4)

#### **Reshape an array**

- arr.reshape() : will give a new shape to an array with out changing the data.

In [14]:
#arr.reshape

a=np.arange(6)
print(a)

b=a.reshape(3,2) #reshaped to 3*2 matrix
print(b) 

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [15]:
np.reshape(a,newshape=(1,6), order='C')

#newshape =shape we want
# a = array to be reshaped

# order = C meands to read/write the elements using C like Index, F meands using Foratan_like index order and A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

array([[0, 1, 2, 3, 4, 5]])

### **Converting 1D array into a 2D array**

- np.newaxis() : will increase the dimensions of array by ome dimension when used once.
- np.expand_dims(): 



In [19]:
#np.newaxis()

a= np.array([1,2,3,4,5])
a.shape

(5,)

In [21]:
a2=a[np.newaxis,:]
a2.shape

(1, 5)

In [22]:
row_vector=a[np.newaxis,:]
row_vector.shape

(1, 5)

In [23]:
column_vector=a[:,np.newaxis]
column_vector.shape

(5, 1)

In [25]:
#np.expand_dims

b=np.expand_dims(a,axis=1)
b.shape

(5, 1)

In [26]:
b=np.expand_dims(a,axis=0)
b.shape

(1, 5)

#### **Indexing and Slicing**

In [ ]:
### Indexing and Slicing