<a href="https://colab.research.google.com/github/aayussraut/Exploring_NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x=np.array([[1,2,3],[4,5,6,6]])
print("x:\n{}".format(x))

x:
[list([1, 2, 3]) list([4, 5, 6, 6])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


## **NumPy**
- extension package to Python for multi-diensional arrays
- closer to hardware
- designed for scinetific computation
- aslo known as array oriented computing.


#### **array**
- is central data structure of the Numpy library.
- the elements in array are of same type

In [ ]:
import numpy as np

In [ ]:
#example
a=np.array([1,2,3,4,5])  # of int type
a=np.array([[1,2,3,4],[4,5,6,7]])  #list type

In [ ]:
#accessing elements

print(a[0])

[1 2 3 4]


##### Attributes of an array

- the no of dimensions and items in an array is defined by iys shape
- the shape of an array is a tuple of nonnegative intergers that specufy the sized of each dimension.

- suppose we have a 2D array that looks like:

[[0., 0., 0.],

 [1., 1., 1.]]

- It means our array has 2 axes. THe first axis has a length of 2 and second axis has a length of 3.



#### **Creating a Basic Array**

-np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [2]:
import numpy as np

In [ ]:
#np.array()
# To create a Numpy array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
#np.zeros()
# to create an array filled with 0's
np.zeros(2)

array([0., 0.])

In [ ]:
#np.ones()
# to cerate an array filled with 1's
np.ones(1)

array([1.])

In [ ]:
#np.zeros

# creates an array whose initial content is random and depends on the state of the memory
# the reasons ti use empty over zeros is speed

np.empty(2)

array([0., 0.])

In [ ]:
#np.arange()

# to create an array with a range of elements

np.arange(4)


array([0, 1, 2, 3])

In [ ]:
# to create an array that contains a range of evenly spaced intervals.

np.arange(2,9,2)


array([2, 4, 6, 8])

In [ ]:
#np.linspace()

# to create an array with values that are spaced linearly in specified interval

np.linspace(0,10,num=5)

# num= 5 means .. 5 no. between 0 and 10

In [ ]:
np.linspace(0,10,num=5 ,endpoint=False)
# returns 5 no between 0 and 10 where 10 is excluded.

array([0., 2., 4., 6., 8.])

In [ ]:
#dtype

#specifying data type

np.ones(2,dtype=np.int64)

array([1, 1])

#### Adding, removing and sorting elements

- np.sort(),np.concatenate()

In [ ]:
#np.sort()

arr=np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#np.partition 

# -rearranges the elements of kth position(i.e. 3 in example) such a way that All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. 
a=np.array([4,2,8,6,10])
np.partition(a,3)

array([ 6,  4,  2,  8, 10])

In [ ]:
#np.concatenate()

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### **Shape and size of array**
- ndarray.ndim : tell us the number of axes,or dimensions, of the array

- ndarray.size : tell us the total number of elements of the array's shape

- ndarray.shape : will display a tuple of integers that indiacate the number of elements stored along each dimension of the array.

In [ ]:
array_example =np.array([[[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]]])


In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

#### **Reshape an array**

- arr.reshape() : will give a new shape to an array with out changing the data.

In [ ]:
#arr.reshape

a=np.arange(6)
print(a)

b=a.reshape(3,2) #reshaped to 3*2 matrix
print(b) 

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape(a,newshape=(1,6), order='C')

#newshape =shape we want
# a = array to be reshaped

# order = C meands to read/write the elements using C like Index, F meands using Foratan_like index order and A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

array([[0, 1, 2, 3, 4, 5]])

### **Converting 1D array into a 2D array**

- np.newaxis() : will increase the dimensions of array by ome dimension when used once.
- np.expand_dims(): 



In [ ]:
#np.newaxis()

a= np.array([1,2,3,4,5])
a.shape

(5,)

In [ ]:
a2=a[np.newaxis,:]
a2.shape

(1, 5)

In [ ]:
row_vector=a[np.newaxis,:]
row_vector.shape

(1, 5)

In [ ]:
column_vector=a[:,np.newaxis]
column_vector.shape

(5, 1)

In [ ]:
#np.expand_dims

b=np.expand_dims(a,axis=1)
b.shape

(5, 1)

In [ ]:
b=np.expand_dims(a,axis=0)
b.shape

(1, 5)

#### **Indexing and Slicing**

- same as slicing python lists.

In [ ]:
### Indexing and Slicing

data =np.array([1,2,3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(a[a<5])

[1 2 3 4]


In [ ]:
five_up =(a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
c=a[(a>5)&(a<11)]
print(c)

[ 6  7  8  9 10]


In [ ]:
c=(a>5) &(a<11)
print(a[c])

[ 6  7  8  9 10]


In [ ]:
c=(a>5) &(a<11)
print(c)

[[False False False False]
 [False  True  True  True]
 [ True  True False False]]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
#print the indices of elements that are less than 5 using np.nonzero()
b=np.nonzero(a<5)
print(b)
# here a tuple of arrays was returned: one for each dimension. THe first array represents the row indices where these value ate found and the second array represents the column indicies where the values are found.

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


### **create an array from existing data**

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

arr1=a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [ ]:
#stack two existing arrays,both verticaly and horizontally,

a1=np.array([[1,1],
            [2,2]])

a2=np.array([[3,3],
             [4,4]])

print(np.vstack((a1,a2)))

print("\n")

print(np.hstack((a1,a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


[[1 1 3 3]
 [2 2 4 4]]


In [ ]:
#spliting an array into several smaller arrays using hsplit.

x=np.arange(1,25).reshape(2,12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [ ]:
print(np.hsplit(x,3))

#split array into three equally shaped arrays.

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


In [ ]:
#split our array after the third and fourth column:
print(np.hsplit(x,(3,4)))

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [ ]:
#slicing and modifying
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
print(b1)
b1[0]=99
print(b1)
print(a)

[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1=a.copy()
b1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### **Basic array operations**

- sum() : sum of the elements in an array

In [4]:
# adding arrays together with the plus sign

data=np.array([1,2])
ones=np.ones(2,dtype=int)
data+ones

array([2, 3])

In [5]:
# more than addition
print(data-ones)
print(data*ones)
print(data/ones)

[0 1]
[1 2]
[1. 2.]


In [6]:
a=np.array([1,2,3,4])

a.sum()

10

In [7]:
b=np.array([[1,1],[2,2]])
b.sum(axis=0)

#sum over the axis of rows

array([3, 3])

In [8]:
b.sum(axis=1)

#sum over the axis of column

array([2, 4])

In [9]:
# operation between an array and a single number
# also called an operation between a vector and a scalar.

data=np.array([1.0,2.0])
data*1.6

array([1.6, 3.2])

In [10]:
data=np.array([1.0,2.0])

print(data.max())
print(data.min())
print(data.sum())

2.0
1.0
3.0


In [12]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
...               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
...               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [13]:
a.sum()

4.8595784

In [14]:
a.min()

0.05093587

In [15]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [16]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

#### **Creating matrices**

In [18]:
# python lists of lists can be used to crfeate a 2-D array (or "matrix")
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
data[0,1]


2

In [20]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [21]:
data[0:2,0]

array([1, 3])