<a href="https://colab.research.google.com/github/aayussraut/Exploring_NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x=np.array([[1,2,3],[4,5,6,6]])
print("x:\n{}".format(x))

x:
[list([1, 2, 3]) list([4, 5, 6, 6])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


## **NumPy**
- extension package to Python for multi-diensional arrays
- closer to hardware
- designed for scinetific computation
- aslo known as array oriented computing.


#### **array**
- is central data structure of the Numpy library.
- the elements in array are of same type

In [ ]:
import numpy as np

In [ ]:
#example
a=np.array([1,2,3,4,5])  # of int type
a=np.array([[1,2,3,4],[4,5,6,7]])  #list type

In [ ]:
#accessing elements

print(a[0])

[1 2 3 4]


##### Attributes of an array

- the no of dimensions and items in an array is defined by iys shape
- the shape of an array is a tuple of nonnegative intergers that specufy the sized of each dimension.

- suppose we have a 2D array that looks like:

[[0., 0., 0.],

 [1., 1., 1.]]

- It means our array has 2 axes. THe first axis has a length of 2 and second axis has a length of 3.



#### **Creating a Basic Array**

-np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [ ]:
import numpy as np

In [ ]:
#np.array()
# To create a Numpy array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
#np.zeros()
# to create an array filled with 0's
np.zeros(2)

array([0., 0.])

In [ ]:
#np.ones()
# to cerate an array filled with 1's
np.ones(1)

array([1.])

In [ ]:
#np.zeros

# creates an array whose initial content is random and depends on the state of the memory
# the reasons ti use empty over zeros is speed

np.empty(2)

array([0., 0.])

In [ ]:
#np.arange()

# to create an array with a range of elements

np.arange(4)


array([0, 1, 2, 3])

In [ ]:
# to create an array that contains a range of evenly spaced intervals.

np.arange(2,9,2)


array([2, 4, 6, 8])

In [ ]:
#np.linspace()

# to create an array with values that are spaced linearly in specified interval

np.linspace(0,10,num=5)

# num= 5 means .. 5 no. between 0 and 10

In [ ]:
np.linspace(0,10,num=5 ,endpoint=False)
# returns 5 no between 0 and 10 where 10 is excluded.

array([0., 2., 4., 6., 8.])

In [ ]:
#dtype

#specifying data type

np.ones(2,dtype=np.int64)

array([1, 1])